name: docker-build-TinyTeX-hithesis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build docker
      run: |
        docker build -t tinytex-hithesis:latest - < .github/workflows/Dockerfile.TinyTeX-hithesis
    - name: Test thesis
      run: |
        docker run --rm -i -v "$PWD":/home/runner tinytex-hithesis:latest make thesis
    - name: Test doc
      run: |
        docker run --rm -i -v "$PWD":/home/runner tinytex-hithesis:latest make doc
