name: MiKTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install MiKTeX
      run:  bash .github/workflows/install-MiKTeX_hithesis.sh
    - name: Test thesis
      run: |
        export PATH="/usr/local/bin:$PATH";
        make thesis
    - name: Test doc
      run: |
        export PATH="/usr/local/bin:$PATH";
        make doc
