name: TeXLive

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: Install TeX Live
      run:  bash .github/workflows/install-TeXLive_hithesis.sh
    - name: Test thesis
      run: |
        export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        make thesis
    - name: Test doc
      run: |
        export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        make doc
